import { Job, CV } from '@/types';

// Mock job data for development
export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'TechCorp Inc.',
    location: 'San Francisco, CA',
    type: 'full-time',
    salary: {
      min: 120000,
      max: 180000,
      currency: 'USD',
    },
    description: 'We are looking for an experienced Frontend Developer to join our dynamic team. You will be responsible for building modern web applications using React and Next.js.',
    requirements: [
      '5+ years of experience with React',
      'Strong TypeScript skills',
      'Experience with Next.js and modern web technologies',
      'Excellent problem-solving skills',
    ],
    benefits: ['Health Insurance', 'Remote Work', '401k', 'Unlimited PTO'],
    postedDate: new Date('2025-10-01'),
    deadline: new Date('2025-11-15'),
    category: 'Engineering',
    remote: true,
    experience: 'senior',
  },
  {
    id: '2',
    title: 'Full Stack Developer',
    company: 'StartupXYZ',
    location: 'New York, NY',
    type: 'full-time',
    salary: {
      min: 90000,
      max: 130000,
      currency: 'USD',
    },
    description: 'Join our fast-growing startup as a Full Stack Developer. Work on cutting-edge projects and make a real impact.',
    requirements: [
      '3+ years full stack experience',
      'Node.js and React proficiency',
      'Database design experience',
      'Startup mentality',
    ],
    benefits: ['Equity', 'Health Insurance', 'Flexible Hours'],
    postedDate: new Date('2025-10-05'),
    category: 'Engineering',
    remote: false,
    experience: 'mid',
  },
  {
    id: '3',
    title: 'UX/UI Designer',
    company: 'DesignStudio',
    location: 'Austin, TX',
    type: 'contract',
    salary: {
      min: 70000,
      max: 100000,
      currency: 'USD',
    },
    description: 'Creative UX/UI Designer needed for a 6-month contract. Design beautiful and intuitive user experiences.',
    requirements: [
      'Strong portfolio demonstrating UX/UI work',
      'Proficiency in Figma and design tools',
      'Understanding of user-centered design',
      'Experience with design systems',
    ],
    postedDate: new Date('2025-10-10'),
    deadline: new Date('2025-10-30'),
    category: 'Design',
    remote: true,
    experience: 'mid',
  },
  {
    id: '4',
    title: 'Junior Backend Developer',
    company: 'CloudTech Solutions',
    location: 'Remote',
    type: 'full-time',
    salary: {
      min: 60000,
      max: 85000,
      currency: 'USD',
    },
    description: 'Entry-level opportunity for passionate developers to work on cloud-based solutions.',
    requirements: [
      '1-2 years programming experience',
      'Knowledge of Python or Node.js',
      'Understanding of REST APIs',
      'Eager to learn',
    ],
    benefits: ['Remote Work', 'Training Budget', 'Health Insurance'],
    postedDate: new Date('2025-10-12'),
    category: 'Engineering',
    remote: true,
    experience: 'entry',
  },
  {
    id: '5',
    title: 'Product Manager',
    company: 'InnovateTech',
    location: 'Seattle, WA',
    type: 'full-time',
    salary: {
      min: 130000,
      max: 170000,
      currency: 'USD',
    },
    description: 'Lead product strategy and execution for our flagship products. Work with cross-functional teams.',
    requirements: [
      '5+ years product management experience',
      'Technical background preferred',
      'Strong analytical skills',
      'Excellent communication',
    ],
    benefits: ['Equity', 'Health Insurance', 'Flexible Schedule', 'Gym Membership'],
    postedDate: new Date('2025-10-08'),
    category: 'Product',
    remote: false,
    experience: 'senior',
  },
];

export const mockCV: CV = {
  id: '1',
  userId: '1',
  personalInfo: {
    fullName: 'John Doe',
    email: 'john.doe@email.com',
    phone: '+1 (555) 123-4567',
    location: 'San Francisco, CA',
    linkedin: 'linkedin.com/in/johndoe',
    portfolio: 'johndoe.dev',
    summary: 'Passionate full-stack developer with 5+ years of experience building scalable web applications. Specialized in React, Node.js, and cloud technologies.',
  },
  experience: [
    {
      id: 'exp1',
      company: 'Tech Company',
      position: 'Senior Developer',
      location: 'San Francisco, CA',
      startDate: new Date('2022-01-01'),
      current: true,
      description: 'Leading development of customer-facing applications',
      achievements: [
        'Reduced application load time by 40%',
        'Mentored 3 junior developers',
        'Implemented CI/CD pipeline',
      ],
    },
    {
      id: 'exp2',
      company: 'Startup Inc',
      position: 'Full Stack Developer',
      location: 'Remote',
      startDate: new Date('2020-03-01'),
      endDate: new Date('2021-12-31'),
      current: false,
      description: 'Built and maintained web applications',
      achievements: [
        'Developed 5+ production features',
        'Improved test coverage to 85%',
      ],
    },
  ],
  education: [
    {
      id: 'edu1',
      institution: 'University of California',
      degree: 'Bachelor of Science',
      field: 'Computer Science',
      location: 'Berkeley, CA',
      startDate: new Date('2016-09-01'),
      endDate: new Date('2020-05-01'),
      gpa: 3.8,
    },
  ],
  skills: [
    'JavaScript',
    'TypeScript',
    'React',
    'Next.js',
    'Node.js',
    'Python',
    'PostgreSQL',
    'MongoDB',
    'AWS',
    'Docker',
    'Git',
  ],
  certifications: [
    {
      id: 'cert1',
      name: 'AWS Certified Developer',
      issuer: 'Amazon Web Services',
      date: new Date('2023-06-15'),
      credentialId: 'AWS-1234567',
    },
  ],
  languages: [
    { name: 'English', proficiency: 'native' },
    { name: 'Spanish', proficiency: 'intermediate' },
  ],
  createdAt: new Date('2025-01-01'),
  updatedAt: new Date('2025-10-01'),
};


